#!/bin/bash
/usr/bin/auth.sh || exit 1
clear
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
CYAN='\033[0;36m'

echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${ORANGE}        AUTOKILL SETUP (OPENVPN)          ${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

if [[ -f /etc/cron.d/ovpn-sniper ]]; then
    STATUS="${GREEN}ACTIVE${NC}"
else
    STATUS="${RED}INACTIVE${NC}"
fi

echo -e " Current Status: $STATUS"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " [1]  AutoKill Every 3 Minutes (Strict)"
echo -e " [2]  AutoKill Every 5 Minutes"
echo -e " [3]  AutoKill Every 10 Minutes"
echo -e " [4]  Turn Off AutoKill"
echo -e " [0]  Back to Menu"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
read -p " Select Option : " req

case $req in
    1)
        echo "*/3 * * * * root /usr/bin/ovpn-sniper" > /etc/cron.d/ovpn-sniper
        echo -e "${GREEN}AutoKill enabled (Every 3 Mins).${NC}"
        service cron restart
        sleep 2
        ;;
    2)
        echo "*/5 * * * * root /usr/bin/ovpn-sniper" > /etc/cron.d/ovpn-sniper
        echo -e "${GREEN}AutoKill enabled (Every 5 Mins).${NC}"
        service cron restart
        sleep 2
        ;;
    3)
        echo "*/10 * * * * root /usr/bin/ovpn-sniper" > /etc/cron.d/ovpn-sniper
        echo -e "${GREEN}AutoKill enabled (Every 10 Mins).${NC}"
        service cron restart
        sleep 2
        ;;
    4)
        rm -f /etc/cron.d/ovpn-sniper
        echo -e "${RED}AutoKill turned off.${NC}"
        service cron restart
        sleep 2
        ;;
    0)
        menu-ovpn.sh
        ;;
    *)
        echo -e "${RED}Invalid Option${NC}"
        sleep 1
        ;;
esac
menu-ovpn.sh
