#!/bin/bash
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
/usr/bin/auth.sh || exit 1

now_exact=$(date +%s)

# Scan through the Linux user database
while IFS=: read -r username password uid gid info home shell; do
    # Only target real users with the VPN restricted shell
    if [[ "$uid" -ge 1000 && "$username" != "nobody" && "$shell" == "/bin/false" ]]; then
        
        expiration=$(chage -l "$username" | grep "Account expires" | cut -d: -f2 | sed 's/^ //g')
        
        if [[ "$expiration" != "never" ]]; then
            exp_date_sec=$(date -d "$expiration" +%s 2>/dev/null)
            
            # If the expiration date has passed
            if [[ $exp_date_sec -lt $now_exact ]]; then
                echo "$(date '+%Y-%m-%d %H:%M:%S') : Deleting Expired User: $username" >> /var/log/ovpn-expire.log
                
                # 1. Completely delete the system user
                /usr/sbin/userdel -f "$username" > /dev/null 2>&1
            fi
        fi
    fi
done < /etc/passwd
