[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0Aa7MYiozYZgdm7jKMB2Eq00AJvlIunVG3WnYJBXQID87znc1HxXYOtVOPmzk2e21zCsudbFAm7Ku9hBrnE85e97NMdkZRx812LkTNDO5nL_R6DgnqKOIJU8eFHG37SOjSaNpzd4ALavt-DIRe_zUia4dOYjE2D25NCpMnNzfSM-XDL5ztCX_cT1qxUqhOndr1d2NwVcaCgYKAXASARESFQHGX2MiDyDcrC6VhN-amztp4HKsSw0206","token_type":"Bearer","refresh_token":"1//01ennH0ovhvP3CgYIARAAGAESNwF-L9IroZEnLqnqYb2Ugfnn307ovWSuLLFx8gQvRa3W8xJcBK1PKwLwH4INK-yDMYcu_b73yXw","expiry":"2026-04-14T08:28:35.5499084Z","expires_in":3599}
team_drive = 